climate/urls.py
from django.conf.urls import url
from . import views
app_name='climate'
urlpatterns=[
url(r'^$',views.HomePage.as_view(),name='home'),
url(r'^detail/(?P<pk>\d+)/$',views.CountryDetail.as_view(),name='detail'),
url(r'^sub_detail/(?P<pk>\d+)/$',views.CountrySubDetail.as_view(),name='sub_detail'),
url(r'^min_detail/(?P<pk>\d+)/$',views.CountryMinDetail.as_view(),name='min_detail'),
url(r'^mean_detail/(?P<pk>\d+)/$',views.CountryMeanDetail.as_view(),name='mean_detail'),
url(r'^rain_detail/(?P<pk>\d+)/$',views.CountryRainDetail.as_view(),name='rain_detail'),
url(r'^sun_detail/(?P<pk>\d+)/$',views.CountrySunnyDetail.as_view(),name='sun_detail'),
url(r'^charts/(?P<tbl>[\w-]+)/(?P<pk>\d+)/(?P<key>\d+)/$',views.ChartView.as_view(),name='charts'),
url(r'login/$',views.UserLogin.as_view(),name='login'),
url(r'^upload/$',views.UploadView.as_view(),name='upload'),
url(r'^update/$',views.Upadate_Data.as_view(),name='update'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from climate.views import UserLogout

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'',include('climate.urls')),
    url(r'^logout/$',UserLogout.as_view(),name='logout'),


]

climate/models.py
from django.db import models
from django.core.urlresolvers import reverse,reverse_lazy

MONTH_CHOICES=(
('JAN','JAN'),('FEB','FEB'),('MAR','MAR'),('APR','APR'),
('MAY','MAY'),('JUN','JUN'),('JUL','JUL'),('AUG','AUG'),
('SEP','SEP'),('OCT','OCT'),('NOV','NOV'),('DEC','DEC'),
)

class Country(models.Model):
    name=models.CharField(max_length=256)

    def __str__(self):
        return self.name

class MaxTemp(models.Model):

    country=models.ForeignKey(Country,on_delete=models.CASCADE,related_name='max_countries')
    temp=models.DecimalField(max_digits=19,decimal_places=2)
    month=models.CharField(max_length=125, choices=MONTH_CHOICES)
    year=models.CharField(max_length=125)

    def __str__(self):
        return self.country.name +' '+self.month+' '+self.year
    class Meta:
        ordering=['-year']

    def get_absolute_url(self):
        return reverse_lazy('climate:sub_detail',kwargs={'pk':self.country.id})

class MinTemp(models.Model):
    country=models.ForeignKey(Country,on_delete=models.CASCADE,related_name='min_countries')
    temp=models.DecimalField(max_digits=19,decimal_places=2)
    month=models.CharField(max_length=125, choices=MONTH_CHOICES)
    year=models.CharField(max_length=125)

    def __str__(self):
        return self.country.name +' '+self.month+' '+self.year
    class Meta:
        ordering=['-year']

    def get_absolute_url(self):
        return reverse_lazy('climate:sub_detail',kwargs={'pk':self.country.id})

class MeanTemp(models.Model):
    country=models.ForeignKey(Country,on_delete=models.CASCADE,related_name='mean_countries')
    temp=models.DecimalField(max_digits=19,decimal_places=2)
    month=models.CharField(max_length=125, choices=MONTH_CHOICES)
    year=models.CharField(max_length=125)

    def __str__(self):
        return self.country.name +' '+self.month+' '+self.year
    class Meta:
        ordering=['-year']

    def get_absolute_url(self):
        return reverse_lazy('climate:sub_detail',kwargs={'pk':self.country.id})

class Rainfall(models.Model):
    country=models.ForeignKey(Country,on_delete=models.CASCADE,related_name='rainfall_countries')
    temp=models.DecimalField(max_digits=19,decimal_places=2)
    month=models.CharField(max_length=125, choices=MONTH_CHOICES)
    year=models.CharField(max_length=125)

    def __str__(self):
        return self.country.name +' '+self.month+' '+self.year
    class Meta:
        ordering=['-year']

    def get_absolute_url(self):
        return reverse_lazy('climate:sub_detail',kwargs={'pk':self.country.id})

class Sunshine(models.Model):
    country=models.ForeignKey(Country,on_delete=models.CASCADE,related_name='sunshine_countries')
    temp=models.DecimalField(max_digits=19,decimal_places=2)
    month=models.CharField(max_length=125, choices=MONTH_CHOICES)
    year=models.CharField(max_length=125)

    def __str__(self):
        return self.country.name +' '+self.month+' '+self.year
    class Meta:
        ordering=['-year']

    def get_absolute_url(self):
        return reverse_lazy('climate:sub_detail',kwargs={'pk':self.country.id})


#Max temp, Min temp, Mean temp, Sunshine,
#and Rainfall for UK, England, Wales, and Scotland regions.

climate/views.py
from django.shortcuts import render,redirect,HttpResponse
import requests
from .fetch_data import rec,scrap_data
from .models import MaxTemp,Country,MinTemp,MeanTemp,Rainfall,Sunshine
from django.views.generic import ListView,DetailView,TemplateView,View
from .generate_table import get_table,chart_data

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.mixins import LoginRequiredMixin

class HomePage(TemplateView):
    template_name='climate/home.html'
    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        context['temp']=Country.objects.all()
        return context

class UserLogin(TemplateView):
    # template_name='climate/login.html'
    def post(self, request):
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            login(request,user)
            return redirect('climate:upload')
        else:
            return HttpResponse('invalid')

    def get(self, request):
        return render(request,'climate/login.html')

class UserLogout(View):
    def get(self,request):
        logout(request)
        return redirect('climate:home')



# def home(request):
#     temp=Country.objects.all()
#     return render(request,'climate/home.html',{'temp':temp})

class UploadView(LoginRequiredMixin,TemplateView):
    template_name='climate/upload.html'


class Upadate_Data(LoginRequiredMixin,View):

    def get(self,request):
        scrap_data(self)
        return render(request,'climate/upload_success.html')

class CountryDetail(DetailView):
    template_name='climate/detail.html'

    def get_context_data(self,*args,**kwargs):
        print(kwargs)

        context=super(CountryDetail,self).get_context_data(*args,**kwargs)
        context['country']=Country.objects.get(pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        return Country.objects.all()


class CountrySubDetail(DetailView):
    template_name='climate/sub_detail.html'

    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        pk=self.kwargs['pk']
        context['data']=get_table(self,MaxTemp,pk)
        context['country']=Country.objects.get(pk=self.kwargs['pk'])
        context['type']='MAX_Temperature'
        return context

    def get_queryset(self):
        return Country.objects.all()

class CountryMinDetail(CountrySubDetail):
    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        pk=self.kwargs['pk']
        context['data']=get_table(self,MinTemp,pk)

        context['type']='MIN_Temperature'
        return context

class CountryMeanDetail(CountrySubDetail):
    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        pk=self.kwargs['pk']
        context['data']=get_table(self,MeanTemp,pk)

        context['type']='MEAN_Temperature'
        return context

class CountryRainDetail(CountrySubDetail):
    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        pk=self.kwargs['pk']
        context['data']=get_table(self,Rainfall,pk)

        context['type']='Rainfall(mm)'
        return context

class CountrySunnyDetail(CountrySubDetail):
    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        pk=self.kwargs['pk']
        context['data']=get_table(self,Sunshine,pk)

        context['type']='Sunshine(Total_hours)'
        return context

class ChartView(TemplateView):
    template_name='climate/charts.html'
    def get_context_data(self,*args,**kwargs):
        context=super().get_context_data(*args,**kwargs)
        pk=self.kwargs['pk']
        key=self.kwargs['key']
        if self.kwargs['tbl']=='MAX_Temperature':
            data=dict(get_table(self,MaxTemp,pk))
            context['max']='Max Temperature'
        if self.kwargs['tbl']=='MIN_Temperature':
            data=dict(get_table(self,MinTemp,pk))
            context['max']='Min Temperature'
        if self.kwargs['tbl']=='MEAN_Temperature':
            data=dict(get_table(self,MeanTemp,pk))
            context['max']='Mean Temperature'
        if self.kwargs['tbl']=='Sunshine(Total_hours)':
            data=dict(get_table(self,Sunshine,pk))
            context['max']='Sunshine(Total hours)'
        if self.kwargs['tbl']=='Rainfall(mm)':
            data=dict(get_table(self,Rainfall,pk))
            context['max']='Rainfall (mm)'
        data=chart_data(self,data[key])
        results = list(map(float, data))
        context['data']=results
        context['country']=Country.objects.get(pk=self.kwargs['pk'])
        context['year']=key


        return context

climate/templates/climate/charts.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
  <div class="col-md-12 py-3">
    <h3>Region : {{country.name}}</h3>
    <h4>Year   : {{year}}</h4>
    <p>Chart for {{max}}</p>
    {% ifequal 'Max Temperature' max %}
    <p> <a href="{% url 'climate:sub_detail' pk=country.id %}">back to list</a> </p>
    {% endifequal %}
    {% ifequal 'Min Temperature' max %}
    <p> <a href="{% url 'climate:min_detail' pk=country.id %}">back to list</a> </p>
    {% endifequal %}
    {% ifequal 'Mean Temperature' max %}
    <p> <a href="{% url 'climate:mean_detail' pk=country.id %}">back to list</a> </p>
    {% endifequal %}
    {% ifequal 'Sunshine(Total hours)' max %}
    <p> <a href="{% url 'climate:sun_detail' pk=country.id %}">back to list</a> </p>
    {% endifequal %}
    {% ifequal 'Rainfall (mm)' max %}
    <p> <a href="{% url 'climate:rain_detail' pk=country.id %}">back to list</a> </p>
    {% endifequal %}
    <canvas id="myChart" width="500px" height="170px"></canvas>
  </div>

</div>


{% endblock %}

{% block javascript %}
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],
        datasets: [{
            label: '',
            data: {{data}},


            backgroundColor: [
               'rgba(255, 99, 132, 0.3)',
               'rgba(54, 162, 235, 0.3)',
               'rgba(255, 206, 86, 0.3)',
               'rgba(75, 192, 192, 0.3)',
               'rgba(153, 102, 255, 0.3)',
               'rgba(255, 159, 64, 0.3)',
               'rgba(255, 99, 132, 0.3)',
               'rgba(54, 162, 235, 0.3)',
               'rgba(255, 200, 86, 0.3)',
               'rgba(75, 192, 12, 0.3)',
               'rgba(153, 12, 255, 0.3)',
               'rgba(255, 159, 69, 0.3)'
           ],
           borderColor: [
               'rgba(255,99,132,1)',
               'rgba(54, 162, 235, 1)',
               'rgba(255, 206, 86, 1)',
               'rgba(75, 192, 192, 1)',
               'rgba(153, 102, 255, 1)',
               'rgba(255, 159, 64, 1)',
               'rgba(255, 99, 132, 1)',
               'rgba(54, 162, 235, 1)',
               'rgba(255, 200, 86, 1)',
               'rgba(75, 192, 12, 1)',
               'rgba(153, 12, 255, 1)',
               'rgba(255, 159, 69, 1)'
           ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
{% endblock %}

climate/templates/climate/detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<h4>  Region Name :  {{country.name}}</h4>
<p>This is the weather report from 1910 of {{country.name}} region.</p>
<hr>
<div class="row ">
  <div class="col py-2">
    <a class="btn btn-danger py-4"  style="height:300px;width:100%" href="{% url 'climate:sub_detail' pk=country.id %}">
      Max Temperature
      <br>  <br>
      <img style="height:150px;width:150px" src="{% static 'img/max.png' %}" alt="">
    </a>

  </div>
  <div class="col py-2">

    <a class="btn btn-info py-4"  style="height:300px;width:100%" href="{% url 'climate:min_detail' pk=country.id %}">
      Min Temperature
      <br>  <br>
      <img style="height:150px;width:150px" src="{% static 'img/min.png' %}" alt="">
    </a>

  </div>
  <div class="col py-2">

    <a class="btn btn-primary py-4" style="height:300px;width:100%" href="{% url 'climate:mean_detail' pk=country.id %}">
      Mean Temperature
      <br>  <br>
      <img style="height:150px;width:150px" src="{% static 'img/mean.png' %}" alt="">
    </a>

  </div>
  <div class="col py-2">

    <a class="btn btn-warning py-4" style="height:300px;width:100%" href="{% url 'climate:sun_detail' pk=country.id %}">
      Sunshine
      <br>  <br>
      <img style="height:150px;width:150px" src="{% static 'img/sunny.png' %}" alt="">
    </a>

  </div>
  <div class="col py-2">

    <a class="btn btn-success py-4" style="height:300px;width:100%" href="{% url 'climate:rain_detail' pk=country.id %}">
      Rainfall
      <br>
      <br>
      <img  style="height:150px;width:150px" src="{% static 'img/rain.png' %}" alt="">
     </a>
  </div>

</div>

{% endblock  %}

climate/templates/climate/home.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
      <div class="col">
        <h1 align='center'>UK and regional series</h1>
        <p align='center'>Weather report dataset from 1910...</p>
      </div>
    </div>
    <div class="row py-3">
        {% for i in temp %}
            <div class="col-md-4 ">
              <a href="{% url 'climate:detail' pk=i.pk %}">
                <div class="alert alert-success " style="align:center;height:120px;width:100%" role="alert">
                   <h3>{{i.name}}</h3>
                   <p >Get detail weather information of {{i.name}} region.</p>


                </div>
              </a>
            </div>
        {% endfor %}
    </div>

    <!-- <div class="row py-3">
        {% for i in temp %}
          <div class="col-md-4 py-2">
            <a href="{% url 'climate:detail' pk=i.pk %}" class="btn btn-success py-4" style="height:100px;width:100%"><span class="pt-3">{{i.name}}</span> </a>
          </div>
        {% endfor %}
    </div> -->

{% endblock  %}

climate/templates/climate/login.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'climate:login' %}" method="post">
  {% csrf_token %}
  <div class="row py-5">
    <div class="col-md-5 mx-auto">
      <input type="text" name="username" value="" placeholder="User Name" class="form-control">
      <br>
       <input type="password" name="password" value="" placeholder='password' class="form-control">
      <br>
      <button type="submit" name="button"  class="btn btn-success">Login</button>


  </div>
  </div>


</form>
{% endblock %}}

climate/templates/climate/sub_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col" >
    <h4 align='center'>Region Name :{{country.name}}</h4>
    <p align='center'>{{type}}</p>
  </div>

</div>

<table class="table table-striped py-3">
  <thead class="table-primary">
    <tr>
      <th scope="col">#</th>
      <th scope="col">YEAR</th>
      <th scope="col">JAN</th>
      <th scope="col">FEB</th>
      <th scope="col">MAR</th>
      <th scope="col">APR</th>
      <th scope="col">MAY</th>
      <th scope="col">JUN</th>
      <th scope="col">JUL</th>
      <th scope="col">AUG</th>
      <th scope="col">SEP</th>
      <th scope="col">OCT</th>
      <th scope="col">NOV</th>
      <th scope="col">DEC</th>
      <th scope="col">Charts</th>
    </tr>
  </thead>
  <tbody>
      {% for key,value in data %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{key}}</td>
        {% for i in value %}
          <td>{{i}}</td>
        {% endfor %}
        <td> <a href="{% url 'climate:charts' tbl=type pk=country.pk key=key %}" class="btn btn-success">chart</a> </td>
        </tr>
      {% endfor %}

  </tbody>
</table>

{% endblock  %}

climate/templates/climate/upload.html
{% extends 'base.html' %}
{% block content %}
<p>Click this button ,It will automatically update new record if it exists..!</p>
<a href="{% url 'climate:update' %}" class="btn btn-success">Update New Record</a>
{% endblock %}

climate/templates/climate/upload_success.html
{% extends "base.html" %}
{% block content %}


<div class="alert alert-success " style="align:center;height:120px;width:100%" role="alert">
  <h3>Record upated successfully..</h3>
</div>
<a href="{% url 'climate:home' %}">go to home page</a>
{% endblock %}