climate/urls.py
from django.conf.urls import url
from . import views
app_name='climate'
urlpatterns=[
url(r'^$',views.HomePage.as_view(),name='home'),
url(r'^detail/(?P<pk>\d+)/$',views.CountryDetail.as_view(),name='detail'),
url(r'^sub_detail/(?P<pk>\d+)/$',views.CountrySubDetail.as_view(),name='sub_detail'),
url(r'^min_detail/(?P<pk>\d+)/$',views.CountryMinDetail.as_view(),name='min_detail'),
url(r'^mean_detail/(?P<pk>\d+)/$',views.CountryMeanDetail.as_view(),name='mean_detail'),
url(r'^rain_detail/(?P<pk>\d+)/$',views.CountryRainDetail.as_view(),name='rain_detail'),
url(r'^sun_detail/(?P<pk>\d+)/$',views.CountrySunnyDetail.as_view(),name='sun_detail'),
url(r'^charts/(?P<tbl>[\w-]+)/(?P<pk>\d+)/(?P<key>\d+)/$',views.ChartView.as_view(),name='charts'),
url(r'login/$',views.UserLogin.as_view(),name='login'),
url(r'^upload/$',views.UploadView.as_view(),name='upload'),
url(r'^update/$',views.Upadate_Data.as_view(),name='update'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from climate.views import UserLogout

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'',include('climate.urls')),
    url(r'^logout/$',UserLogout.as_view(),name='logout'),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% include 'css.html' %}
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container py-3">

        {% block content %}
        {% endblock %}


    </div>

    {% include 'js.html' %}
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

templates/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" type="text/javascript">

</script>

templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">


  <a class="navbar-brand" href="{% url 'climate:home' %}"> <img class="mr-2"style="height:40px;wigth:40px"src="{% static 'img/weatherfrontapp_logo.png' %}" alt="no">  Weather Report</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav ml-auto ">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'climate:home' %}">Home</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'climate:upload' %}">Upload Records</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Logout</span></a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'climate:login' %}">Login</span></a>
      </li>
      {% endif %}

    </ul>

  </div>
    </div>
</nav>